export const products = [
  {
    id: "1",
    name: "Everyday Minimalist Necklace",
    price: 899,
    category: "Necklaces",
    description: "A delicate, everyday chain that adds a subtle touch of elegance to any outfit. Perfect for layering.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Keep away from perfumes and harsh chemicals. Store in the provided pouch.",
    images: ["/placeholder.jpg"], // We will handle images later
    stock: 5,
    isFeatured: true,
  },
  {
    id: "2",
    name: "Classic Pearl Studs",
    price: 499,
    category: "Earrings",
    description: "Timeless pearl studs set in a minimal gold frame. An absolute essential for your jewelry box.",
    material: "Sterling Silver base, Faux Pearl",
    finish: "18K Gold Plated",
    careInstructions: "Wipe with a soft cloth after use.",
    images: ["/placeholder.jpg"],
    stock: 2,
    isFeatured: true,
  },
  {
    id: "3",
    name: "Twisted Rope Ring",
    price: 399,
    category: "Rings",
    description: "A beautifully textured twisted rope design. Anti-tarnish and perfect for daily wear.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Water-resistant, but avoid prolonged exposure to chemicals.",
    images: ["/placeholder.jpg"],
    stock: 0, // Out of stock example
    isFeatured: false,
  },
  {
    id: "4",
    name: "Crystal Drop Nose Pin",
    price: 299,
    category: "Nose Pins",
    description: "A tiny, elegant crystal drop that catches the light beautifully.",
    material: "Sterling Silver",
    finish: "Silver",
    careInstructions: "Clean gently with silver polish if needed.",
    images: ["/placeholder.jpg"],
    stock: 10,
    isFeatured: true,
  },
  {
    id: "5",
    name: "Snake Chain Bracelet",
    price: 699,
    category: "Bracelets",
    description: "A fluid, smooth snake chain that sits comfortably on the wrist.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Store flat to prevent kinking.",
    images: ["/placeholder.jpg"],
    stock: 4,
    isFeatured: false,
  },
  {
    id: "6",
    name: "Beaded Anklet",
    price: 450,
    category: "Anklets",
    description: "A delicate chain with spaced golden beads. Perfect for summer days.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Rinse with fresh water if worn in the sea.",
    images: ["/placeholder.jpg"],
    stock: 3,
    isFeatured: false,
  },
   {
    id: "7",
    name: "Beaded Anklet",
    price: 450,
    category: "Anklets",
    description: "A delicate chain with spaced golden beads. Perfect for summer days.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Rinse with fresh water if worn in the sea.",
    images: ["/placeholder.jpg"],
    stock: 3,
    isFeatured: false,
  },
   {
    id: "8",
    name: "Beaded Anklet",
    price: 450,
    category: "Anklets",
    description: "A delicate chain with spaced golden beads. Perfect for summer days.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Rinse with fresh water if worn in the sea.",
    images: ["/placeholder.jpg"],
    stock: 3,
    isFeatured: false,
  },
   {
    id: "9",
    name: "Beaded Anklet",
    price: 450,
    category: "Anklets",
    description: "A delicate chain with spaced golden beads. Perfect for summer days.",
    material: "Stainless Steel",
    finish: "18K Gold Plated",
    careInstructions: "Rinse with fresh water if worn in the sea.",
    images: ["/placeholder.jpg"],
    stock: 3,
    isFeatured: false,
  }
];